[Interface]
PrivateKey = GHVzY29tZXNhY2tqZGtsZmdoamhrc2hkZmpraHNkZms=
Address = 10.200.0.5/24

[Peer]
PublicKey = sKfUgTH+HLrkJX+cSaJLeWhpN/cruHnULI43fOhY124=
Endpoint = setulink.example.com:51820
AllowedIPs = 192.168.10.0/24
PersistentKeepalive = 25

