"""add_subnet_registry

Revision ID: 2a645b2e58bb
Revises: fdb0fcf82aac
Create Date: 2026-06-30 17:19:50.811904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a645b2e58bb'
down_revision: Union[str, Sequence[str], None] = 'fdb0fcf82aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('router_zt_ip', sa.String(), nullable=True),
    sa.Column('lan_subnet', sa.String(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('zt_interface', sa.String(), nullable=True),
    sa.Column('claimed_state', sa.Enum('pending', 'allocating_table', 'provisioning_zt', 'provisioning_wg', 'active', 'failed', name='subnetprovisioningstate'), nullable=True),
    sa.Column('health', sa.Enum('healthy', 'degraded', 'unreachable', 'unknown', name='subnethealth'), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('router_id')
    )
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subnet_registry_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subnet_registry_table_id'), ['table_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subnet_registry_table_id'))
        batch_op.drop_index(batch_op.f('ix_subnet_registry_id'))

    op.drop_table('subnet_registry')
    # ### end Alembic commands ###
