"""add_provisioning_started_at_and_sequence

Revision ID: 3370927432a1
Revises: 3cc67ff58ea2
Create Date: 2026-06-30 17:30:42.787480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3370927432a1'
down_revision: Union[str, Sequence[str], None] = '3cc67ff58ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provisioning_started_at', sa.DateTime(), nullable=True))

    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE SEQUENCE gateway_table_id_seq START 100 MAXVALUE 10000")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP SEQUENCE IF EXISTS gateway_table_id_seq")
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.drop_column('provisioning_started_at')

    # ### end Alembic commands ###
