"""add_component_status_to_subnet_registry

Revision ID: 3cc67ff58ea2
Revises: 2a645b2e58bb
Create Date: 2026-06-30 17:22:40.727358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc67ff58ea2'
down_revision: Union[str, Sequence[str], None] = '2a645b2e58bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_status', sa.Enum('PENDING', 'APPLIED', 'FAILED', 'UNKNOWN', name='componentstatus'), nullable=True))
        batch_op.add_column(sa.Column('route_status', sa.Enum('PENDING', 'APPLIED', 'FAILED', 'UNKNOWN', name='componentstatus'), nullable=True))
        batch_op.add_column(sa.Column('forward_status', sa.Enum('PENDING', 'APPLIED', 'FAILED', 'UNKNOWN', name='componentstatus'), nullable=True))
        batch_op.add_column(sa.Column('nat_status', sa.Enum('PENDING', 'APPLIED', 'FAILED', 'UNKNOWN', name='componentstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.drop_column('nat_status')
        batch_op.drop_column('forward_status')
        batch_op.drop_column('route_status')
        batch_op.drop_column('policy_status')

    # ### end Alembic commands ###
