"""add_desktop_peer_and_ip_octet

Revision ID: 6e1f5f052e3d
Revises: 783508ab9e5c
Create Date: 2026-06-30 18:03:02.713592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1f5f052e3d'
down_revision: Union[str, Sequence[str], None] = '783508ab9e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktop_peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('wg_ip', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('endpoint_ip', sa.String(), nullable=True),
    sa.Column('last_handshake', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('desktop_peers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desktop_peers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_desktop_peers_public_key'), ['public_key'], unique=True)

    with op.batch_alter_table('table_allocators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_wg_ip_octet', sa.Integer(), nullable=False, server_default='2'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_allocators', schema=None) as batch_op:
        batch_op.drop_column('next_wg_ip_octet')

    with op.batch_alter_table('desktop_peers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desktop_peers_public_key'))
        batch_op.drop_index(batch_op.f('ix_desktop_peers_id'))

    op.drop_table('desktop_peers')
    # ### end Alembic commands ###
