"""table_allocator_and_retry_count

Revision ID: 783508ab9e5c
Revises: 3370927432a1
Create Date: 2026-06-30 17:50:49.967560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783508ab9e5c'
down_revision: Union[str, Sequence[str], None] = '3370927432a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_allocators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_table_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_allocators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_allocators_id'), ['id'], unique=False)

    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))

    # Seed the allocator row (dialect portable)
    op.execute("INSERT INTO table_allocators (id, next_table_id) VALUES (1, 100)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet_registry', schema=None) as batch_op:
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('table_allocators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_allocators_id'))

    op.drop_table('table_allocators')
    # ### end Alembic commands ###
