"""initial schema

Revision ID: fdb0fcf82aac
Revises: 
Create Date: 2026-06-30 10:35:44.392171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb0fcf82aac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='tenantstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('system_owner', 'master', 'second_master', 'admin', 'trusted', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('force_otp', sa.Boolean(), nullable=True),
    sa.Column('email_otp_code_hash', sa.String(), nullable=True),
    sa.Column('email_otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_otp_attempts', sa.Integer(), nullable=True),
    sa.Column('email_otp_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('routers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('zerotier_node_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('prepared', 'pending_validation', 'claimed', name='routerstatus'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('router_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_routers_id'), 'routers', ['id'], unique=False)
    op.create_table('activation_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('key_code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_code'),
    sa.UniqueConstraint('router_id')
    )
    op.create_index(op.f('ix_activation_keys_id'), 'activation_keys', ['id'], unique=False)
    op.create_table('pending_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('serial_number_submitted', sa.String(), nullable=False),
    sa.Column('key_code_submitted', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'syncing', 'failed', 'completed', name='pendingvalidationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('fail_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_validations_id'), 'pending_validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_validations_id'), table_name='pending_validations')
    op.drop_table('pending_validations')
    op.drop_index(op.f('ix_activation_keys_id'), table_name='activation_keys')
    op.drop_table('activation_keys')
    op.drop_index(op.f('ix_routers_id'), table_name='routers')
    op.drop_table('routers')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
